version: '3'
services:
    app:
        image: vicenterusso/php-nginx-alpine:8
        volumes:
            - "./etc/nginx/vhosts:/etc/nginx/conf.d"
            - "./etc/ssl:/var/www/ssl"
            - "./web/projectfolder:/var/www/html"
        ports:
            - "80:8080"
            - "443:4443"   